In [1]:
import numpy as np

In [2]:
#normal
A =np.array([[121,100],[113,93],[112,92]]) #22,24 
y = np.array([[110],[103],[102]])#23
m, c,_,_ = np.linalg.lstsq(A, y)
print m

[[ 1.23461911]
 [-0.39361261]]


In [36]:
#x1 = R*0.299 + G*0.587 + B*0.114
x1 = (121*0.299)+(113*0.587)+(112*0.114)
x2 = (100*0.299)+(93*0.587)+(92*0.114)
x3 = (110*0.299)+(103*0.587)+(102*0.114) #mid 
print x1,x2,x3

115.278 94.979 104.979


In [37]:
# a1 = (x3-x2)/x1-x2
a1 = (x3-x2)/(x1-x2)
print a1,1-a1

0.492635105178 0.507364894822


In [111]:
%matplotlib inline

In [33]:
# import matplotlib.pyplot as plt
# plt.imshow([[(121.0, 113.0, 112.0)]])

In [34]:
# import matplotlib.pyplot as plt
# plt.imshow([[(100.0, 93.0, 92.0)]])

In [31]:
# import matplotlib.pyplot as plt
# plt.imshow([[(110.0, 103.0, 102.0)]])

In [83]:
#bright
A =np.array([[170,140],[158,130],[158,130]]) #22,24
y = np.array([[155],[144],[144]])#23
m, c,_,_ = np.linalg.lstsq(A, y)
print m

[[ 0.5]
 [ 0.5]]


In [6]:
#x1 = R*0.299 + G*0.587 + B*0.114
x1 = (170*0.299)+(158*0.587)+(158*0.114)
x2 = (140*0.299)+(130*0.587)+(130*0.114)
x3 = (155*0.299)+(144*0.587)+(144*0.114) #mid 
print x1,x2,x3
# a1 = (x3-x2)/x1-x2
a2 = (x3-x2)/(x1-x2)
print a2

161.588 132.99 147.289
0.5


In [84]:
#darker
A =np.array([[68,56],[64,53],[64,53]]) #22,24
y = np.array([[62],[59],[59]])#23
m, c,_,_ = np.linalg.lstsq(A, y)
print m

[[-0.9]
 [ 2.2]]


In [7]:
#x1 = R*0.299 + G*0.587 + B*0.114
x1 = (68*0.299)+(64*0.587)+(64*0.114)
x2 = (56*0.299)+(53*0.587)+(53*0.114)
x3 = (62*0.299)+(59*0.587)+(59*0.114) #mid 
print x1,x2,x3
# a1 = (x3-x2)/x1-x2
a3 = (x3-x2)/(x1-x2)
print a3

65.196 53.897 59.897
0.531020444287


In [90]:
#normal
A =np.array([[206,181],[203,177],[203,177]]) #15,17 
y = np.array([[194],[190],[190]])#16
m, c,_,_ = np.linalg.lstsq(A, y)
print m

[[ 0.18505338]
 [ 0.86120996]]


In [9]:
#x1 = R*0.299 + G*0.587 + B*0.114
x1 = (206*0.299)+(203*0.587)+(203*0.114)
x2 = (181*0.299)+(177*0.587)+(177*0.114)
x3 = (194*0.299)+(190*0.587)+(190*0.114) #mid 
print x1,x2,x3
# a1 = (x3-x2)/x1-x2
a1 = (x3-x2)/(x1-x2)
print a1,1-a1

203.897 178.196 191.196
0.505816894284


In [12]:
# r1 = 1.23461911/0.18505338
# r2 = -0.39361261/0.86120996
# c1 = 1.23461911/-0.39361261
# c2 =0.18505338/0.86120996
# print r1,r2
# print c1,c2,c1/c2

In [68]:
#bright
A =np.array([[224,208],[219,202],[219,202]]) #15,17 
y = np.array([[110],[103],[102]])#16
m, c,_,_ = np.linalg.lstsq(A, y)
print m

[[-2.96052632]
 [ 3.71710526]]


In [30]:
#x1 = R*0.299 + G*0.587 + B*0.114
x1 = (224*0.299)+(219*0.587)+(219*0.114)
x2 = (208*0.299)+(202*0.587)+(202*0.114)
x3 = (110*0.299)+(103*0.587)+(102*0.114) #mid 
print x1,x2,x3
# a1 = (x3-x2)/x1-x2
a2 = (x3-x2)/(x1-x2)
print a2,1-a2

220.495 203.794 104.979
-5.91671157416 6.91671157416


In [69]:
#dark
A =np.array([[121,100],[113,93],[112,92]]) #15,17 
y = np.array([[110],[103],[102]])#16
m, c,_,_ = np.linalg.lstsq(A, y)
print m

[[ 1.23461911]
 [-0.39361261]]


In [29]:
#x1 = R*0.299 + G*0.587 + B*0.114
x1 = (121*0.299)+(113*0.587)+(112*0.114)
x2 = (100*0.299)+(93*0.587)+(92*0.114)
x3 = (110*0.299)+(103*0.587)+(102*0.114) #mid 
print x1,x2,x3
# a1 = (x3-x2)/x1-x2
a3 = (x3-x2)/(x1-x2)
print a3

115.278 94.979 104.979
0.492635105178


In [79]:
#normal
A =np.array([[169,100],[164,93],[164,92]]) #18,24
y = np.array([[133],[125],[125]])#21
m, c,_,_ = np.linalg.lstsq(A, y)
print m

[[ 0.27466909]
 [ 0.86488519]]


In [18]:
#x1 = R*0.299 + G*0.587 + B*0.114
x1 = (169*0.299)+(164*0.587)+(164*0.114)
x2 = (100*0.299)+(93*0.587)+(92*0.114)
x3 = (133*0.299)+(125*0.587)+(125*0.114) #mid 
print x1,x2,x3
# a1 = (x3-x2)/x1-x2
a1 = (x3-x2)/(x1-x2)
print a1,1-a1

165.495 94.979 127.392
0.459654546486 0.540345453514


In [15]:
# import matplotlib.pyplot as plt
# plt.imshow([[(169.0, 164.0, 164.0)]])

In [16]:
# import matplotlib.pyplot as plt
# plt.imshow([[(100.0, 93.0, 92.0)]])

In [17]:
# import matplotlib.pyplot as plt
# plt.imshow([[(133.0, 125.0, 125.0)]])

In [80]:
#bright
A =np.array([[200,140],[193,130],[193,130]]) #18,24
y = np.array([[177],[166],[166]])#21
m, c,_,_ = np.linalg.lstsq(A, y)
print m

[[ 0.2254902 ]
 [ 0.94215686]]


In [19]:
#x1 = R*0.299 + G*0.587 + B*0.114
x1 = (200*0.299)+(193*0.587)+(193*0.114)
x2 = (140*0.299)+(130*0.587)+(130*0.114)
x3 = (177*0.299)+(166*0.587)+(166*0.114) #mid 
print x1,x2,x3
# a1 = (x3-x2)/x1-x2
a2 = (x3-x2)/(x1-x2)
print a2,1-a2

195.093 132.99 169.289
0.584496723186 0.415503276814


In [20]:
# import matplotlib.pyplot as plt
# plt.imshow([[(200.0, 193.0, 193.0)]])

In [21]:
# import matplotlib.pyplot as plt
# plt.imshow([[(140.0, 130.0, 130.0)]])

In [22]:
# import matplotlib.pyplot as plt
# plt.imshow([[(177.0, 166.0, 166.0)]])

In [81]:
#darker
A =np.array([[136,56],[133,53],[133,53]]) #18,24
y = np.array([[85],[81],[81]])#21
m, c,_,_ = np.linalg.lstsq(A, y)
print m

[[ 0.12916667]
 [ 1.20416667]]


In [23]:
#x1 = R*0.299 + G*0.587 + B*0.114
x1 = (136*0.299)+(133*0.587)+(133*0.114)
x2 = (56*0.299)+(53*0.587)+(53*0.114)
x3 = (85*0.299)+(81*0.587)+(81*0.114) #mid 
print x1,x2,x3
# a1 = (x3-x2)/x1-x2
a3 = (x3-x2)/(x1-x2)
print a3,1-a3

133.897 53.897 82.196
0.3537375 0.6462625


In [92]:
#normal Red 
A =np.array([[217,209],[60,17],[106,13]]) #18,24
y = np.array([[213],[38],[89]])#21
m, c,_,_ = np.linalg.lstsq(A, y)
print m

[[ 0.76214712]
 [ 0.22489664]]


In [28]:
#x1 = R*0.299 + G*0.587 + B*0.114
x1 = (217*0.299)+(60*0.587)+(106*0.114)
x2 = (209*0.299)+(17*0.587)+(13*0.114)
x3 = (213*0.299)+(38*0.587)+(89*0.114) #mid 
print x1,x2,x3
# a1 = (x3-x2)/x1-x2
a1 = (x3-x2)/(x1-x2)
print a1,1-a1

112.187 73.952 96.139
0.580279848307 0.419720151693


In [96]:
#bright
A =np.array([[255,255],[62,20],[116,86]]) #18,24
y = np.array([[255],[41],[101]])#21
m, c,_,_ = np.linalg.lstsq(A, y)
print m

[[ 0.5]
 [ 0.5]]


In [27]:
#x1 = R*0.299 + G*0.587 + B*0.114
x1 = (255*0.299)+(62*0.587)+(116*0.114)
x2 = (255*0.299)+(20*0.587)+(86*0.114)
x3 = (255*0.299)+(41*0.587)+(101*0.114) #mid 
print x1,x2,x3
# a1 = (x3-x2)/x1-x2
a2 = (x3-x2)/(x1-x2)
print a2,1-a2

125.863 97.789 111.826
0.5 0.5


In [98]:
#dark
A =np.array([[213,204],[59,16],[102,69]]) #18,24
y = np.array([[208],[47],[85]])#21
m, c,_,_ = np.linalg.lstsq(A, y)
print m

[[ 0.6528501 ]
 [ 0.33174593]]


In [25]:
#x1 = R*0.299 + G*0.587 + B*0.114
x1 = (213*0.299)+(59*0.587)+(102*0.114)
x2 = (204*0.299)+(16*0.587)+(69*0.114)
x3 = (208*0.299)+(47*0.587)+(85*0.114) #mid 
print x1,x2,x3
# a1 = (x3-x2)/x1-x2
a3 = (x3-x2)/(x1-x2)
print a3,1-a3

109.948 78.254 99.471
0.669432700196 0.330567299804
